### ISSUE TITLE
Use C11 standard atomics

### ISSUE THREAD

**Issue by jscott0** [tavianator/oomify#1]
Hi,

I notice some of the code uses instructions like GCC's __atomic_fetch_add. This seems unnecessary; these built-ins are primarily for standard C library implementers to implement atomics. If the only reason the stats have to be atomic is to avoid problems with multiple threads writing at the same time, making the struct members of type atomic_size_t and incrementing just using, say, `stats.free++` should suffice. I could send a pull request if you could help me get my head around this.

**Comment by tavianator** [comment]
To be honest I have no idea why I used the `__atomic` intrinsics instead of the standard ones.  I think originally I had written the code as part of a separate project that is C99 so I didn't rely on `<stdatomic.h>`.  But yeah I have no objections to using the standard ones.
